- name: heisenberg
  #corporate_net: "disconnected"
  tasks:
    - playbooks/host/tasks_host_default.yaml
    # Red Hat specific configurations
    #- playbooks/host/tasks_host_rh.yaml
    - playbooks/host/tasks_host_rpm_ostree.yaml
    - playbooks/host/tasks_host_systemd.yaml
    #- playbooks/host/tasks_host_env.yaml
    - playbooks/host/tasks_host_python.yaml
    - playbooks/host/tasks_host_gnome_extensions.yaml
    - playbooks/host/tasks_host_gnome_dconf.yaml
    #- playbooks/host/tasks_host_etc.yaml

  layered_packages:
    - { name: langpacks-en, state: present }
    - { name: langpacks-it, state: present }
    - { name: pass, state: present } # TODO: move into toolbox
    - { name: krb5-workstation, state: present }
    - { name: vim-enhanced, state: present }
    - { name: distrobox, state: present }
    - { name: make, state: present }
    - { name: gcc, state: present }
    - { name: golang, state: present }
    - { name: rust, state: present }
    - { name: cargo, state: present }
    - { name: libvirt, state: present }
    - { name: libvirt-devel, state: present }
    - { name: libvirt-nss, state: present }
    - { name: libvirt-client, state: present }
    - { name: virt-manager, state: present }
    - { name: virt-install, state: present }
    - { name: python3-lxml, state: present }
    - { name: python3-netaddr, state: present }
    - { name: python3-devel, state: present }

  local_packages:
    bins: # this files are just downloaded as-is and placed in ~/.local/bin
    #  - { name: jq, url: "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64" }
      - { name: yq, url: "https://github.com/mikefarah/yq/releases/download/v4.19.1/yq_linux_amd64" }
      - { name: ocm, url: "https://github.com/openshift-online/ocm-cli/releases/download/v0.1.63/ocm-linux-amd64" }
    archives: # Here you can define a list of archives to download and exctract the files defined by `include`
      - url: https://github.com/todbot/blink1-tool/releases/download/v2.2.0/blink1-tool-v2.2.0-linux-x86_64.zip
        include:
          - blink1-tool
      - url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-4.11/openshift-client-linux.tar.gz
        include:
          - oc
          - kubectl
      - url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-4.11/opm-linux.tar.gz
        include:
          - opm
      - url: https://git.sr.ht/~gpanders/ijq/refs/download/v0.3.8/ijq-0.3.8-linux-amd64.tar.gz
        include:
          - ijq
      - url: https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip 
        include:
          - terraform

  pip_packages:
    - { name: pip, state: latest }
    - { name: powerline-status, state: latest }
    - { name: powerline-gitstatus, state: latest }
    - { name: powerline-gitstatus, state: latest }
    - { name: o-must-gather, state: latest }

  git_config:
    - { name: core.editor, scope: global, value: vim }
    - { name: user.name, scope: global, value: Gianni Salinetti }
    - { name: user.email, scope: global, value: gsalinet@redhat.com }
    - { name: init.defaultBranch, scope: global, value: main }

  gnome:
    extensions: {{ lookup('template', 'configs/host_gnome_extensions.yaml') | from_yaml }}
    dconf: {{ lookup('template', 'configs/host_gnome_dconf.yaml') | from_yaml }}

  user_systemd_services:
    - { name: podman.socket, state: started, enabled: yes }

  systemd_services:
    - { name: libvirtd.service, state: started, enabled: yes }
