- name: fedora-toolbox-36
  image: registry.fedoraproject.org/fedora-toolbox:36
  shims:
    - flatpak
    - systemctl
    - rpm-ostree
    - podman
  packages: # packages to install
    - oathtool
    - restic
    - nmap
    - openssl
    - strace
    - tcpdump
  cmds: # wrap those toolbox commands from the host
    - oathtool
    - restic
    - nmap
    - openssl
    - strace
    - tcpdump
  user: # configure the user
    groups: wheel
  toolbox_tasks: 
    - playbooks/toolbox/tasks_toolbox_default.yaml
    - playbooks/toolbox/tasks_dnf_full_upgrade.yaml
    - playbooks/toolbox/tasks_dnf_common_packages.yaml
    - playbooks/toolbox/tasks_toolbox_host_shims.yaml
    - playbooks/toolbox/tasks_fedora_system.yaml


- name: devel-fedora-36
  image: registry.fedoraproject.org/fedora-toolbox:36
  shims:
    - flatpak
    - systemctl
    - rpm-ostree
    - podman
  user:
    groups: wheel,mock
  toolbox_tasks: 
    - playbooks/toolbox/tasks_toolbox_default.yaml
    - playbooks/toolbox/tasks_dnf_full_upgrade.yaml
    - playbooks/toolbox/tasks_dnf_common_packages.yaml
    - playbooks/toolbox/tasks_toolbox_host_shims.yaml
    - playbooks/toolbox/tasks_fedora_devel.yaml

